Vagrant.configure("2") do |config| 
  config.vm.box = "spox/ubuntu-arm" 
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.19"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.ssh_info_public = true
    vmware.gui = true
   end
 end
