Vagrant.configure("2") do |config|
    config.vm.box = "jacobw/fedora35-arm64"
    config.vm.network "private_network", ip: "192.168.56.88"
    config.vm.provider "vmware_desktop" do |v|
        v.gui = true
        v.memory = "1024"
    end
end
